name: init
on: push
jobs:
  build:
    name: Build project
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout main branch
      uses: actions/checkout@main
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - run: npm run deploy-static