name: init
on: push
jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@main
      - name: Install packages
        with:
          node-version: 12.x
      - run: npm install